### ISSUE TITLE
Tests do not compile in play 2.4 example

### ISSUE THREAD

**Issue by tashiscool** [adamw/macwire#92]
Are you seeing the tests not compile/pass in the play 2.4 example?
[error] /Users/tashdidkhan/.Trash/macwire-master/examples/play24/test/com/softwaremill/play24/controllers/CoffeeControllerSpec.scala:17: object creation impossible, since method dbConfig in trait ControllerModule of type => slick.backend.DatabaseConfig[slick.driver.JdbcProfile] is not defined
[error]     "return all" in new ControllerContext {
[error]                         ^
[error] /Users/tashdidkhan/.Trash/macwire-master/examples/play24/test/com/softwaremill/play24/controllers/CoffeeControllerSpec.scala:35: object creation impossible, since method dbConfig in trait ControllerModule of type => slick.backend.DatabaseConfig[slick.driver.JdbcProfile] is not defined
[error]     "return priced by coffee, supplier" in new ControllerContext {
[error]                                                ^
[error] two errors found
[error] (test:compileIncremental) Compilation failed

**Comment by adamw** [comment]
Just did a clean build and everything is fine. Do you have the latest sources? There's no `dbConfig` in `ControllerModule`? (https://github.com/adamw/macwire/blob/master/examples/play24/app/com/softwaremill/play24/modules/ControllerModule.scala)

**Comment by tashiscool** [comment]
my mistake.  Thanks for checking
