### ISSUE TITLE
Play 2.4 example does not compile with Macwire 2.0

### ISSUE THREAD

**Issue by guersam** [adamw/macwire#82]
I tried to update Play example to use Macwire 2.0, but it fails to compile with the following errors:
```
[error] /home/guersam/workspace/github/macwire/examples/play24/app/com/softwaremill/play24/AppApplicationLoader.scala:36: Found multiple values of type [slick.driver.H2Driver.api.Database]: [List(db, db)]
[error]   val seed = wire[Seed]
[error]                  ^
[error] /home/guersam/workspace/github/macwire/examples/play24/app/com/softwaremill/play24/AppApplicationLoader.scala:31: Cannot find a value of type: [String]
[error]   lazy val router: Router = wire[Routes] withPrefix "/"
[error]                                 ^
[error] two errors found
[error] (compile:compileIncremental) Compilation failed
```
It seems that macwire 2.0
 - recognizes overridden (abstract) member as another value
 - does not take secondary constructors into account (even if it's annotated with `@javax.inject.Inject()`)

**Comment by adamw** [comment]
Regarding `Routes` and the fact that a non-primary constructor was wired - I'm surprised that every worked ;) Maybe when there are multiple constructors, we should give preference to the one annotated with `@Inject`, and if that fails do the primary? @backuitist what do you think?

**Comment by adamw** [comment]
`List(db, db)` is a bug, looking into that

**Comment by backuitist** [comment]
Yep, I know the issue, I've fixed it but I'm waiting on #80 ;)

**Comment by adamw** [comment]
See https://github.com/adamw/macwire/pull/83

**Comment by adamw** [comment]
For some reason the `@Inject` on `Routes` annotation is not visible to the macro during compile-time, so until somebody has an idea why is that I added a `prefix` dependency

**Comment by gregsilin** [comment]
@adamw, what version is the fix / how do I apply it?  This still doesn't work with macwire 2.1.0

**Comment by adamw** [comment]
What exactly doesn't work? The example contained in the sources works as far as I know

**Comment by gregsilin** [comment]
Sorry, didn't realize that this was specifically for the Play example.  Here are the snippet generating the compiler error:

in build.sbt
````
routesGenerator := play.routes.compiler.InjectedRoutesGenerator

````

in routes
````
POST        /api/events                    controllers.EventsController.postEvent()
````

in app/controllers/EventsController.scala
````
class EventsController() extends Controller {
  def unauthenticatedDocumentEvent() = Action.async {
    Future(Results.Accepted)(scala.concurrent.ExecutionContext.Implicits.global)
  }
}
````

**Comment by gregsilin** [comment]
I should add that reverting to `1.0.7` fixed the issue.

**Comment by adamw** [comment]
I'm quite surprised that it works in `1.0.7`.
Now, as for this specific situation, the wiring should use the constructor annotated with `@Inject` (which doesn't have the prefix), but for some reason, the annotation is not visible at compile-time to the macro, and the constructor with the prefix is chosen.

As a work-around, I can propose:

```
  lazy val router: Router = {
    lazy val prefix = "/"
    wire[Routes]
  }
```

**Comment by gregsilin** [comment]
@adamw thanks, your suggested fix worked!  One thing that's interesting is that the `actorSystem` defined as a lazy val in the `BuiltInComponents` trait was no longer being pulled in by `2.1.0` so I had to manually define it:

````scala
      lazy val appActorSystem: ActorSystem = actorSystem
````

**Comment by adamw** [comment]
@gregsilin Sorry I only got to it now, I tried this and it works, I added a top-level `class Z(as: ActorSystem)` and then in the `trait AppComponents extends BuiltInComponents`: `wire[Z]` and it compiled just fine. Is that you scenario?

**Comment by ScalaWilliam** [comment]
Isn't prefix supposed to be passed in from config or something? It's weird to set it as default in the application loader like this.
